name: document_scanner_plus
description: A plugin that creates a native platform view that scans documents, as a flutter widget.
version: 1.0.1
homepage: https://github.com/SunnatilloShavkatov/document_scanner_plus

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  plugin:
    platforms:
      android:
        package: uz.shs.document_scanner_plus
        pluginClass: DocumentScannerPlugin
      ios:
        pluginClass: DocumentScannerPlugin
